name: MarkSchenker
favicon: null
layout_spectrum: 0.37199171748943627
typography_spectrum: 0.19806733774021268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23732626158744097
  lightness: 0.6026002890430391
  saturation: 0.37776070344261825
  rhythmicContrast: 0.7313135978765786
purpose: []
