name: Mark Schenker
favicon: null
layout_spectrum: 0.95979
typography_spectrum: 0.1538
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Mark Schenker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#66a6e3'
    - '#faf6f5'
    - '#0091e0'
    - '#081c34'
    - '#9b5650'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.7313135978765786
purpose: []
