name: MarkSchenker
favicon: null
layout_spectrum: 0.24885
typography_spectrum: 0.1980673377402127
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: One. Click. Voice.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.237326261587441
  lightness: 0.6026002890430391
  saturation: 0.3777607034426183
  rhythmicContrast: 0.7313135978765786
purpose: []
